### ISSUE TITLE
I get a black screen when using this

### ISSUE THREAD

**Issue by eladgel** [wix-playground/react-native-navigation-v1-v2-adapter#18]
followed the instructions and tried implementing this with the v1 example project, which was working fine prior.
Now as you can see below I get a black screen :/
I've tested this on rn 57.1

![image](https://user-images.githubusercontent.com/412137/46383219-179d1580-c664-11e8-8534-7ae0bb5b8716.png)

**Comment by cyberpolin** [comment]
Be sure to change the import of "react-native-navigation" to "react-native-navigation-v1-v2-adapter"

**Comment by WwaLlasS** [comment]
Be sure to change the import of "react-native-navigation" to "react-native-navigation-v1-v2-adapter"

**Comment by eladgel** [comment]
Problem was with the RNN version 2.0.555 works!
